package com.example.mbg.demo.mybatisgeneratorexample.mbg.model;

public class Shift {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shift.id
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shift.date
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shift.day
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private String day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shift.end_time
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shift.start_time
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shift.title
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shift.user_user_id
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private Integer userUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shift.id
     *
     * @return the value of shift.id
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shift.id
     *
     * @param id the value for shift.id
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shift.date
     *
     * @return the value of shift.date
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shift.date
     *
     * @param date the value for shift.date
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shift.day
     *
     * @return the value of shift.day
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shift.day
     *
     * @param day the value for shift.day
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setDay(String day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shift.end_time
     *
     * @return the value of shift.end_time
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shift.end_time
     *
     * @param endTime the value for shift.end_time
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shift.start_time
     *
     * @return the value of shift.start_time
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shift.start_time
     *
     * @param startTime the value for shift.start_time
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shift.title
     *
     * @return the value of shift.title
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shift.title
     *
     * @param title the value for shift.title
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shift.user_user_id
     *
     * @return the value of shift.user_user_id
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public Integer getUserUserId() {
        return userUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shift.user_user_id
     *
     * @param userUserId the value for shift.user_user_id
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setUserUserId(Integer userUserId) {
        this.userUserId = userUserId;
    }
}