package com.example.mbg.demo.mybatisgeneratorexample.mbg.model;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.create_at
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.fname
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.lname
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private String lname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.status
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.update_at
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.create_at
     *
     * @return the value of users.create_at
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.create_at
     *
     * @param createAt the value for users.create_at
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.fname
     *
     * @return the value of users.fname
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.fname
     *
     * @param fname the value for users.fname
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setFname(String fname) {
        this.fname = fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.lname
     *
     * @return the value of users.lname
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.lname
     *
     * @param lname the value for users.lname
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setLname(String lname) {
        this.lname = lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.status
     *
     * @return the value of users.status
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.status
     *
     * @param status the value for users.status
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.update_at
     *
     * @return the value of users.update_at
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.update_at
     *
     * @param updateAt the value for users.update_at
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }
}