package com.example.mbg.demo.mybatisgeneratorexample.mbg.mapper;

import com.example.mbg.demo.mybatisgeneratorexample.mbg.model.Shift;
import com.example.mbg.demo.mybatisgeneratorexample.mbg.model.ShiftExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shift
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    long countByExample(ShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shift
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    int deleteByExample(ShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shift
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shift
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    int insert(Shift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shift
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    int insertSelective(Shift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shift
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    List<Shift> selectByExample(ShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shift
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    Shift selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shift
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    int updateByExampleSelective(@Param("record") Shift record, @Param("example") ShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shift
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    int updateByExample(@Param("record") Shift record, @Param("example") ShiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shift
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    int updateByPrimaryKeySelective(Shift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shift
     *
     * @mbg.generated Fri Mar 06 23:45:38 EST 2020
     */
    int updateByPrimaryKey(Shift record);
}