server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: thumbnail
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /

aws:
  region: us-east-1
  credentials:
    access-key: minioadmin
    secret-key: minioadmin
  s3:
    endpoint: http://localhost:9000

spring.cloud.stream.defaultBinder: rabbit

spring.cloud:
  function:
    definition: thumbnailMessageProcessor;
  stream:
    default:
      contentType: application/json
    bindings:
      thumbnailMessageProcessor-in-0:
        destination: thumbnail
        group: thumbnailGroup

---
spring.config.activate.on-profile: docker

spring:
  rabbitmq:
    host: rabbitmq
