spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
