# Enabling H2 Console, http://localhost:8080/h2-console
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:postgresql://localhost/cisc4900db
    username: postgres
    password:
    driverClassName: org.postgresql.Driver